### ISSUE TITLE
Error to read .edr file

### ISSUE THREAD

**Issue by leonqli** [chemlab/chemlab#119]
def test_read_edr():
    df = datafile('data/ener.edr')
    #df.read('frames')

    dt, temp = df.read('quantity', 'Temperature')
    unit = df.read('units', 'Temperature')

    try:
        df.read('quantity', 'NonExistent')
    except:
        pass

-----------
Traceback (most recent call last):
  File "a.py", line 24, in <module>
    test_read_edr()
  File "a.py", line 14, in test_read_edr
    dt, temp = df.read('quantity', 'Temperature')
  File "/usr/local/lib/python2.7/dist-packages/chemlab-0.3-py2.7-linux-x86_64.egg/chemlab/io/handlers/edr.py", line 69, in read
    self.frames = frames = self.process_frames()        
  File "/usr/local/lib/python2.7/dist-packages/chemlab-0.3-py2.7-linux-x86_64.egg/chemlab/io/handlers/edr.py", line 111, in process_frames
    self._unpack_start()
  File "/usr/local/lib/python2.7/dist-packages/chemlab-0.3-py2.7-linux-x86_64.egg/chemlab/io/handlers/edr.py", line 129, in _unpack_start
    raise Exception('Format not supported: magic number -55555 not matching')
Exception: Format not supported: magic number -55555 not matching

**Comment by gabrielelanaro** [comment]
I'll close because this is likely a change in gromacs format. Trying to catch up with gromacs format changes is a lost cause, we need gromacs devs to write a decent API for their data analysis
