### ISSUE TITLE
QtViewer does not properly handles window resize

### ISSUE THREAD

**Issue by jaimergp** [chemlab/chemlab#131]
I am following the example provided in https://chemlab.readthedocs.org/en/latest/graphics.html, and everything works ok (I did have to install pillow due to the missing PIL dependency). However, I have observed that the QtViewer does not handle resizing properly. It's like color and light got separated at resizing.

The molecule depicted is PDB 1JJ2, and I also applied some post-processing: SSAO (kernel size 128) and FXAA.

Furthermore, the window resize action raises a ValueError.

```
Traceback (most recent call last):
  File "/home/jr/.local/anaconda3/envs/mychemlab/lib/python3.4/site-packages/chemlab-0.4.1-py3.4-linux-x86_64.egg/chemlab/graphics/qchemlabwidget.py", line 226, in resizeGL
    self.textures['color'].delete()
  File "/home/jr/.local/anaconda3/envs/mychemlab/lib/python3.4/site-packages/chemlab-0.4.1-py3.4-linux-x86_64.egg/chemlab/graphics/textures.py", line 29, in delete
    glDeleteTextures(self.id)
  File "/home/jr/.local/anaconda3/envs/mychemlab/lib/python3.4/site-packages/OpenGL/latebind.py", line 61, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/home/jr/.local/anaconda3/envs/mychemlab/lib/python3.4/site-packages/OpenGL/GL/exceptional.py", line 59, in glDeleteTextures
    ptr = arrays.GLuintArray.asArray( size )
  File "/home/jr/.local/anaconda3/envs/mychemlab/lib/python3.4/site-packages/OpenGL/arrays/arraydatatype.py", line 149, in asArray
    return cls.getHandler(value).asArray( value, typeCode or cls.typeConstant )
  File "/home/jr/.local/anaconda3/envs/mychemlab/lib/python3.4/site-packages/OpenGL/arrays/arraydatatype.py", line 53, in __call__
    typ.__module__, type.__name__, repr(value)[:50]
TypeError: No array-type handler for type numpy.type (value: 1) registered
```

OK:
![qt_ok](https://cloud.githubusercontent.com/assets/2559438/7979283/3644a62c-0a9e-11e5-878d-74075306039a.png)

Resized:
![qt_resized](https://cloud.githubusercontent.com/assets/2559438/7979282/3643b0be-0a9e-11e5-9d57-f5b3451af231.png)

**Comment by gabrielelanaro** [comment]
Interesting, it looks like there's some error with PyOpenGL (maybe it's a new version) that doesn't clean up the screen properly on resize, do you have the code you used?

**Comment by jaimergp** [comment]
Yup, fixed! Thanks!
